version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: locationregisterapi-mongo
    restart: always
    ports:
      - "27017:27017"          # Mongo accesible localmente
    volumes:
      - mongo-data:/data/db    # Persistencia de la DB
      - mongo-logs:/data/log   # Logs de Mongo
    command: ["mongod", "--dbpath", "/data/db", "--logpath", "/data/log/mongo.log", "--bind_ip_all"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locationregisterapi-app
    ports:
      - "8080:8080"             # API accesible localmente
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/LocationRegisterDB"
      PORT: 8080
    command: sh -c "./.build/release/LocationRegisterAPI serve --env development --hostname 0.0.0.0 --port 8080"
    volumes:
      - .:/app                 # Monta c√≥digo local para desarrollo en caliente

volumes:
  mongo-data:
  mongo-logs:
